homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('portofolio/',views.portofolio, name='portofolio'),
    path('gallery/',views.gallery, name='gallery'),
    path('project/',views.project, name='project'),
    path('project/story1',views.story1, name='story1'),
    path('project/comingsoon',views.comingsoon, name='comingsoon'),
    # dilanjutkan ...
]

jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    path('tambah/', views.tambah_jadwal, name='tambah_jadwal'),
    path('detail/<int:index>/', views.detail_jadwal, name='detail_jadwal'),

    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('story7/', include('story7.urls')),
    path('',  include('story8.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'
urlpatterns = [
    path('story8/', views.showBook, name="story8"),
    path('data/', views.dataBook, name="data"),
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models
# Create your models here.
SEMESTER_CHOICES = ( 
    ("Gasal 2020/2021", "Gasal 2020/2021"),
    ("Genap 2019/2020", "Genap 2019/2020"), 
    ("Gasal 2019/2020", "Gasal 2019/2020"),
    ("dll", "dll"),
) 

# ini buat detail jadwal yang ada
class Jadwal(models.Model):
    matkul = models.CharField('Matakuliah', max_length=120, null=True)
    dosen = models.CharField('Dosen', max_length=120, null=True)
    sks = models.IntegerField('SKS', null=True)
    
    semester = models.CharField('Semester', 
    max_length=120, null=True,
    choices = SEMESTER_CHOICES, 
    default = 'Gasal 2020/2021'
    )  

    deskripsi = models.TextField('Deskripsi', max_length=100, null=True)
    kelas = models.CharField('Kelas', max_length=120, null=True, default='Kamar Pribadi')

    def __str__(self):
        return self.matkul

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django.forms import ModelForm
from .models import Jadwal


class SubjectForm(ModelForm):
    required_css_class = 'required'
# fields that are automatically generated depend on the content of the 
# Meta class and on which fields have already been defined declaratively
    class Meta:
        model = Jadwal
        fields = '__all__'

homepage/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'index.html')

def profile(request):
    return render(request, 'profile.html')

def portofolio(request):
    return render(request, 'portofolio.html')

def gallery(request):
    return render(request, 'gallery.html')

def project(request):
    return render(request, 'project.html')

def story1(request):
    return render(request, 'story1.html')

def comingsoon(request):
    return render(request, 'comingsoon.html')
# Create your views here.

jadwal/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from .models import Jadwal
from .forms import SubjectForm
import datetime


def jadwal(request):
    if request.method == "POST":
        Jadwal.objects.get(id=request.POST['id']).delete()
        return redirect('/jadwal/')
    list_jadwal = Jadwal.objects.all()
    return render(request, 'list_jadwal.html', {'list_jadwal': list_jadwal})

def tambah_jadwal(request):
    submit = False
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            # return render(request, 'subject_add.html')
            return HttpResponseRedirect('/jadwal/tambah/?submit=True')
    else:
        form = SubjectForm()
        if 'submit' in request.GET:
            submit = True
    return render(request, 'tambah_jadwal.html', {'form': form, 'submit': submit})


def detail_jadwal(request, index):
    jadwal = Jadwal.objects.get(pk=index)
    return render(request, 'detail_jadwal.html', {'jadwal': jadwal})

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def showBook(request):
    html = 'story8.html'
    return render(request, html)

def showBook(request):
    html = 'story8.html'
    return render(request, html)
    
def process(data):
    books = data["items"] if "items" in data else ''
    booksJson = []
    if books != '':
        for book in books:
            content = book["volumeInfo"]

            imageLinks = content["imageLinks"] if "imageLinks" in content else ''
            imageUrl = imageLinks["smallThumbnail"] if imageLinks != '' else ''

            title = content["title"] if "title" in content else ''
            
            authors = content["authors"] if "authors" in content else ''
            authorData = ''
            if (authors != '') :
                for author in authors[:-1]:
                    authorData += author + ', '
                authorData += authors[-1]
            else:
                authorData = '-'

            publisher = content["publisher"] if "publisher" in content else ''
            publisher = publisher if publisher != '' else '-'

            categories = content["categories"] if "categories" in content else '-'

            bookDict = {
                "imageLinks": imageUrl,
                "title": title,
                "authors": authorData,
                "publisher": publisher,
                "categories": categories
            }

            booksJson.append(bookDict)

    else:
        booksJson.append({"error": "Mohon maaf buku tidak dapat ditemukan"})
        
    return booksJson

def dataBook(request):
    querry = request.GET.get('querryBook')
    querry = querry if querry != '' else 'Adbis'
    request_url = 'https://www.googleapis.com/books/v1/volumes?q=' + querry
    book_request = requests.get(request_url)
    data = json.loads(book_request.content)
    bookJson = process(data)
    return JsonResponse(bookJson, safe=False)

homepage/templates/comingsoon.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block title %} Coming Soon {% endblock %}

{% block main_body %}
{% include "navbar.html" %}
<div class="container-fluid" style="max-height: 100vh; padding-top: 15%">
    <p class="comingsoon">Tunggu Deadline Pacil</p>
</div>
{% endblock %}

homepage/templates/gallery.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% block title %} gallery {% endblock %}

{% block main_body %}
{% include "navbar.html" %}
<div class="bg-gallery"> 
    <div class="container-fluid mt-3 bg-kontur2">

        <!-- embed video youtube -->
        <div class="col-12 text-center">
            <h1 id="karya">Gallery</h1>
            <div class="wrapper">
                <div class="video-wrapper">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/HYX66uNwBpg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
        </div>

        <!-- gallery -->
        <section style="margin-top:5%" class="no-touch">
            <div class="wrap">
                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '1.jpg' %}" />
                        <div class="titleBox">Pemandangan</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '2.jpg' %}"/>
                        <div class="titleBox">Bakau</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '3.jpg' %}"/>
                        <div class="titleBox">Teluk Ijo</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '4.jpg' %}"/>
                        <div class="titleBox">Pantai</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '5.jpg' %}"/>
                        <div class="titleBox">Keluarga</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '6.jpg' %}"/>
                        <div class="titleBox">Osis</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '7.jpg' %}"/>
                        <div class="titleBox">Teman</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '8.jpg' %}"/>
                        <div class="titleBox">Jembatan</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '9.jpg' %}"/>
                        <div class="titleBox">Impian</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '10.jpg' %}"/>
                        <div class="titleBox">Pulau</div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '11.jpg' %}"/>
                        <div class="titleBox">Saudara</div>
                    </div>
                </div>

                <div class="box">
                    <div class="boxInner">
                        <img src="{% static '1.jpg' %}" />
                        <div class="titleBox">Pemandangan</div>
                    </div>
                </div>

            </div>
        </section>
    </div>
</div>
{% endblock %}

</html>

homepage/templates/navbar.html
<nav class="navbar sticky-top navbar-expand-sm bg-dark navbar-dark" style="padding-left: 3%;">
    <a class="navbar-brand"href="{% url 'homepage:index' %}">
        <svg width="30" height="30" viewBox="0 0 62 62" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g clip-path="url(#clip0)">
            <path d="M44.5261 43.4589H40.6525C40.4108 44.7399 39.2864 45.7096 37.9355 45.7096H34.8627L34.8632 45.7086C34.129 46.5946 33.0945 47.2251 31.9101 47.4422C33.3916 50.5018 36.5258 52.6119 40.153 52.6119H53.3579C53.5372 52.6119 53.6795 52.462 53.6734 52.2827C53.5003 47.3803 49.4711 43.4589 44.5261 43.4589Z" fill="#D7D7D7"/>
            <path d="M27.1373 45.7091H24.065C22.7136 45.7091 21.5892 44.7399 21.3475 43.4589H17.4739C12.5289 43.4589 8.49973 47.3798 8.32661 52.2827C8.32046 52.462 8.46284 52.6114 8.64211 52.6114H21.847C25.4746 52.6114 28.6089 50.5013 30.0899 47.4413C28.9059 47.2251 27.8719 46.5946 27.1373 45.7091Z" fill="#D7D7D7"/>
            <path d="M36.1167 42.1551C35.4341 32.2594 35.2246 29.0584 35.1432 27.9254C35.112 27.4879 35.0108 27.0587 34.8433 26.656L34.8225 26.6055C34.1887 25.0771 32.7384 24.0863 31.1339 24.0863H31.1112C29.4982 24.0863 28.0295 25.0751 27.3966 26.6138C27.3923 26.6231 27.3885 26.6325 27.3848 26.6418C27.2159 27.0489 27.1109 27.4805 27.0792 27.9229C27.0205 28.7435 26.8053 31.9121 26.6918 33.5852C26.6497 34.2076 26.3091 34.7634 25.7893 35.0778C23.1706 36.662 21.4101 39.6045 21.4101 42.9752C21.4101 44.5595 22.6484 45.8436 24.1763 45.8436H26.3299C26.8597 45.8436 27.3753 46.0388 27.7707 46.4052C28.6553 47.2253 29.8232 47.7266 31.1117 47.7266C34.0222 47.7266 36.3224 45.1662 36.1167 42.1551V42.1551Z" fill="white"/>
            <path d="M22.3026 45.2145L27.3112 45.215C30.21 45.215 32.5007 42.6543 32.2958 39.6427C31.2425 24.2997 31.3193 25.0478 31.2534 24.6485C31.1724 24.4758 31.0942 24.3017 31.0207 24.1246C31.0155 24.1113 31.0089 24.0991 31.0033 24.0863C32.5893 24.1172 34.0099 25.114 34.6383 26.6362C34.7118 26.8133 34.79 26.9874 34.871 27.1601C34.9209 27.4628 35.1993 31.5977 35.3312 33.5829C35.3727 34.2059 35.7118 34.7617 36.2295 35.0762C38.8367 36.6612 40.5899 39.6035 40.5899 42.9746C40.5899 44.5586 39.3567 45.8429 37.8353 45.8429C37.8353 45.8429 36.5922 45.8429 35.6906 45.8429C35.1626 45.8424 34.6496 46.0381 34.2558 46.4045C33.375 47.2248 32.212 47.7266 30.9293 47.7266C29.6462 47.7266 28.4832 47.2248 27.6023 46.4045C27.209 46.0386 26.6956 45.8429 26.1675 45.8429H24.0229C23.3719 45.8429 22.7737 45.6079 22.3022 45.215L22.3026 45.2145Z" fill="white"/>
            <path d="M61.0918 19.2099H58.9419C58.6203 19.2099 58.3398 18.9971 58.2475 18.6891C56.6227 13.2626 51.5855 9.44531 45.816 9.44531C39.9378 9.44531 34.8201 13.4078 33.2965 18.9975C31.7795 18.6617 30.2205 18.6617 28.7035 18.9975C27.1799 13.4078 22.0622 9.44531 16.184 9.44531C10.4145 9.44531 5.37732 13.2626 3.75249 18.6891C3.66025 18.9971 3.37975 19.2099 3.05809 19.2099H0.908203C0.406799 19.2099 0 19.6167 0 20.1181V24.7272C0 25.2291 0.406799 25.6355 0.908203 25.6355H3.05809C3.37975 25.6355 3.66072 25.8483 3.75249 26.1562C5.37732 31.5828 10.4145 35.4001 16.184 35.4001C21.3759 35.4001 26.0569 32.3178 28.1089 27.5479C28.6089 26.3861 29.7437 25.6355 31 25.6355C32.2563 25.6355 33.3911 26.3861 33.8911 27.5474C35.9431 32.3178 40.6241 35.4001 45.816 35.4001C51.5855 35.4001 56.6227 31.5828 58.2475 26.1562C58.3398 25.8483 58.6203 25.6355 58.9419 25.6355H61.0918C61.5932 25.6355 62 25.2287 62 24.7272V20.1181C62 19.6167 61.5932 19.2099 61.0918 19.2099ZM54.1355 22.4227C54.1355 27.0101 50.4034 30.7427 45.816 30.7427C41.2282 30.7427 37.496 27.0105 37.496 22.4227C37.496 17.8348 41.2282 14.1027 45.816 14.1027C50.4034 14.1027 54.1355 17.8353 54.1355 22.4227V22.4227ZM24.513 22.4227C24.513 27.0153 20.7766 30.7512 16.184 30.7512C11.5919 30.7512 7.85548 27.0153 7.85548 22.4227C7.85548 17.8301 11.5919 14.0942 16.184 14.0942C20.7766 14.0942 24.513 17.8301 24.513 22.4227Z" fill="#EF5350"/>
            <path d="M61.0918 19.2099H58.9419C58.6203 19.2099 58.3398 18.9971 58.2475 18.6891C56.6227 13.2626 51.5855 9.44531 45.816 9.44531C39.9378 9.44531 34.8201 13.4078 33.2965 18.9975C31.7795 18.6617 30.2205 18.6617 28.7035 18.9975C27.1799 13.4078 22.0622 9.44531 16.184 9.44531C10.4145 9.44531 5.37732 13.2626 3.75249 18.6891C3.66025 18.9971 3.37975 19.2099 3.05809 19.2099H0.908203C0.406799 19.2099 0 19.6167 0 20.1181V24.7272C0 25.2291 0.406799 25.6355 0.908203 25.6355H3.05809C3.37975 25.6355 3.66072 25.8483 3.75249 26.1562C5.37732 31.5828 10.4145 35.4001 16.184 35.4001C21.3759 35.4001 26.0569 32.3178 28.1089 27.5479C28.6089 26.3861 29.7437 25.6355 31 25.6355C32.2563 25.6355 33.3911 26.3861 33.8911 27.5474C35.9431 32.3178 40.6241 35.4001 45.816 35.4001C51.5855 35.4001 56.6227 31.5828 58.2475 26.1562C58.3398 25.8483 58.6203 25.6355 58.9419 25.6355H61.0918C61.5932 25.6355 62 25.2287 62 24.7272V20.1181C62 19.6167 61.5932 19.2099 61.0918 19.2099ZM54.1355 22.4227C54.1355 27.0101 50.4034 30.7427 45.816 30.7427C41.2282 30.7427 37.496 27.0105 37.496 22.4227C37.496 17.8348 41.2282 14.1027 45.816 14.1027C50.4034 14.1027 54.1355 17.8353 54.1355 22.4227V22.4227ZM24.513 22.4227C24.513 27.0153 20.7766 30.7512 16.184 30.7512C11.5919 30.7512 7.85548 27.0153 7.85548 22.4227C7.85548 17.8301 11.5919 14.0942 16.184 14.0942C20.7766 14.0942 24.513 17.8301 24.513 22.4227Z" fill="white"/>
            </g>

        </svg>  
    </a>
<ul class="navbar-nav ml-auto mt-2 mt-lg-0" style="padding-right: 10px;">
    <li class="nav-item">
    <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'homepage:gallery' %}">Gallery</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'homepage:project' %}">Project</a>
    </li>
</ul>
</nav>

homepage/templates/project.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% block title %} Project {% endblock %}

{% block main_body %}
{% include "navbar.html" %}  
<div class="bg-gallery bg-kontur2"> 
    <div class="container-fluid" style="min-height: 88vh; padding:15px">

        <!-- kebutuhan card -->
        <div class="col-12 d-flex align-items-center justify-content-center text-center">  
            <a href="{% url 'homepage:story1' %}" style="color: black;">
                <div class="card mb-3 animasi-card" style="max-width: 350px;margin:40px">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <img src="{% static 'card.jpg' %}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-title">Story 1</p>
                        </div>
                        </div>
                    </div>
                </div>
            </a>  
            <a href="{% url 'jadwal:jadwal' %}" style="color: black;">
                <div class="card mb-3 animasi-card" style="max-width: 350px; margin:40px">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <img src="{% static 'card.jpg' %}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-title">Jadwal Kuliah</p>
                        </div>
                        </div>
                    </div>
                </div>
            </a>  
        </div>
    <div class="col-12 d-flex align-items-center justify-content-center text-center">  
            <a href="{% url 'story7:story7' %}" style="color: black;">
                <div class="card mb-3 animasi-card" style="max-width: 350px;margin:40px">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <img src="{% static 'card.jpg' %}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-title">Story 7</p>
                        </div>
                        </div>
                    </div>
                </div>
            </a>  
            <a href="{% url 'story8:story8' %}" style="color: black;">
                <div class="card mb-3 animasi-card" style="max-width: 350px; margin:40px">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <img src="{% static 'card.jpg' %}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-title">Story 8</p>
                        </div>
                        </div>
                    </div>
                </div>
            </a>  
        </div>
    </div>
</div>
{% endblock %}

jadwal/templates/detail_jadwal.html
{% extends "base.html" %}
{% block title %} detail jadwal {% endblock %}

{% block main_body %}
{% include "navbar.html" %}  
<div class="container-fluid pt-3 m-auto text-center mx-auto bg-kontur2" style="min-height: 89vh;">
    <div class="row align-items-center justify-content-center" style="margin-top:5%">
        <div class="col-md-4">
            <div class="section-title m-auto text-center p-5">
                <h1>{{ jadwal.matkul }}</h1>
            </div>
        </div>
        <div class="col-5" style="max-width: 100%;">
            <table class="table table-bordered mx-5 bg-light" style="width:30vw;">
                <tbody>
                <tr>
                    <td><b>Dosen</b></td>
                    <td>{{ jadwal.dosen }}</td>
                </tr>
            
                <tr>
                    <td><b>SKS</b></td>
                    <td>{{ jadwal.sks }}</td>
                </tr>
            
                <tr>
                    <td><b>Semester</b></td>
                    <td>{{ jadwal.semester }}</td>
                </tr>
            
                <tr>
                    <td><b>Kelas</b></td>
                    <td>{{ jadwal.kelas }}</td>
                </tr>
            
                <tr>
                    <td><b>Deskripsi</b></td>
                    <td>{{ jadwal.deskripsi }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-2">
            <a href="{% url 'jadwal:jadwal' %}" >
            <button class="btn click bg-dark text-white">
                Back
            </button>
            </a>
        </div>
        </div>
    </div>
</div>

{% endblock %}

jadwal/templates/list_jadwal.html
{% extends "base.html" %}

{% block title %} list_jadwal {% endblock %}
{% block main_body %}
{% include "navbar.html" %}  
<div class="container-fluid col-12">
    <section class="container-fluid d-flex flex-wrap align-content-center mb-5">
        <div class="section-title mx-auto text-center p-5">
            <h1>Jadwal Sibuk</h1>
        </div>
        <table class="table table-bordered table-hover mb-5 m-auto " style="width:90vw">
            <thead class="thead-light text-center">
            <tr>
                <th>Mata Kuliah</th>
                <th>Dosen</th>
                <th>SKS</th>
                <th>Deskripsi</th>
                <th>Hapus</th>
            </tr>
            </thead>
            <tbody>
            
            <!-- Menampilkan list matakuliah yang ada -->
            
            {% for x in list_jadwal %}
                <tr class="text-center" style="font-family: 'Montserrat', sans-serif;"> 
                    <td style="vertical-align: middle;">
                        <a href="detail/{{ x.id }}">
                            <button class="btn bg-dark mx-auto mt-2 text-white" style="font-size: 0.8rem;">
                                {{ x.matkul }}
                            </button>
                        </a>
                    </td>
                    <td style="vertical-align: middle;">{{ x.dosen }}</td>
                    <td style="vertical-align: middle;">{{ x.sks }}</td>
                    <td style="vertical-align: middle;">{{ x.deskripsi }}</td>
                    <td style="vertical-align: middle;">
                        <form method="POST" action="{% url 'jadwal:jadwal' %}">
                            {% csrf_token %}
                            <input name="id" value="{{x.id}}" type="hidden" />
                            <button type="submit" value="Submit" class="btn bg-dark mx-auto mt-2 text-white" style="font-size: 0.8rem;">
                                Hapus
                            </button>
                        </form>
                    </td>
                </tr>
            </a>
            {% endfor %}
        
        
            </tbody>
        </table>
        <a href="{% url 'jadwal:tambah_jadwal' %}" class="m-auto pt-3">
        <!-- button ngelink ke page jadwal -->
            <button class="btn bg-dark click text-white">
                Tambah Jadwal Baru
            </button>
        </a>
        </section>
        
</div>

{% endblock %}

jadwal/templates/tambah_jadwal.html
{% extends "base.html" %} 
{% block title %} Jadwal Baru {% endblock %}
{% block main_body %}
{% include "navbar.html" %}  
<section class="container-fluid d-flex flex-wrap align-content-center ">

<!-- Kalau pengguna sudah pencet tambah jadwal -->
{% if submit %}
<div class="success p-5 col-12 text-center">
    <h1>
        Berhasil
    </h1>
    <h1>
        Menambahkan Jadwal
    </h1>
</div>
<div class="col-12 text-center">
    <div class="row d-flex" >
    <div class="col-6">
        <a href="{% url 'jadwal:tambah_jadwal' %}" class="text-center">
            <button class="btn bg-dark d-flex m-auto click text-white" style="padding: 10%; font-family:'Montserrat', sans-serif;">
                Tambah
            </button>
        </a>
    </div>
    <div class="col-6">
        <a href="{% url 'jadwal:jadwal' %}">
            <button class="btn bg-dark d-flex m-auto click text-white"  style="padding: 10%; font-family:'Montserrat', sans-serif;">
                Kembali
            </button>
        </a>
    </div>
</div>
</div>


<!-- Saat pengguna mengisi form tambah jadwal-->
{% else %}
<section class="section-title mx-auto text-center p-5">
    <h1>Tambah Jadwal</h1>
</section>

<form action="" method="post" novalidate>
    {% csrf_token %}
    <table class="table mx-5 " style="width:90vw">
    {{ form.as_table }}
    <tr>
        <td>&nbsp;</td>
        <td>
            <input type="submit" value="Submit" class="btn bg-success click text-white" />
        </td>

    </tr>
    </table>
</form>

</section>
{% endif %} {% endblock %}

story8/templates/story8.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
{% endblock meta %}

{% block title %}Story 8{% endblock %}

{% block main_body %}
{% include "navbar.html" %}
<main class="container" style="min-height: 90vh;">
    <h1 class="pt-5" style="text-align: center;">Cari Buku</h1>
    <p style="text-align: center;">Cari buku penunjang mata kuliah yang kalian butuhkan!</p>
    <div style="margin:4vw;">
        <div class="form-inline d-flex justify-content-center md-form form-sm mt-2">
            <input  type="search" name="queryBook" id="queryBook" class="form-control form-control-sm ml-3 w-75" placeholder="Tulis judul buku ..."
            style="padding:1.5vw">
        </div>
    </div>

    <div class="table-responsive mt-5">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Cover</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Publisher</th>
                    <th>Category</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    
</main>
{% endblock%}

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'story8.js' %}"></script>
{% endblock script %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.2-dist\css\bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'bootstrap-4.5.2-dist\js\bootstrap.js' %}"></script>
    {% block meta %}
    {% endblock meta %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% block main_body %}
        {% endblock %}
    </div>
    
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    <!-- <script src="../static/scripts/app.js"></script> -->
    {% block script %}    
    {% endblock script %}

</body>
</html>